name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          node -v
          npm install
          node ./create-pdf.js
      - uses: actions/upload-artifact@v1
        with:
          name: resume-en
          path: ./README.pdf
      - run: node ./create-pdf-ja.js
      - uses: actions/upload-artifact@v1
        with:
          name: resume-ja
          path: ./ja/README.pdf
